<?php
/**
* @name       routestartenddays.phtml
* @since      16 feb, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
	
<link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css">

    <!-- Custom styles for this template -->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css">

<script type="text/javascript" src= "https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script>
<script type="text/javascript" src= "https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script>
        $(document).ready(function () {
			var currentDate = new Date();
			var day = currentDate.getDate();
			var month = currentDate.getMonth() + 1;
			var year = currentDate.getFullYear();

			var d = day + "-" + month + "-" + year;
            $('#example').dataTable({
				scrollX: true,
				paging: false,
				scrollCollapse: true,
				scrollY: '400px',
                dom: 'Bfrtip',
				"columnDefs": [
    { "width": "10%", "targets": 2 }
  ],
                buttons: [
                    'csv', 
					{
						extend: 'excelHtml5',
						title: d+' -MTD SUMMARY'
					}, 
					'pdf'
                ]
            });
			
        });
    </script>

<div class="card shadow margin-info" style="margin: 20px">
	<div class = "row">
		<div class="col-4"></div>
		<div class="col-4"><p class="text-center"><b><u>MTD SUMMARY Report</u></b></p></div>
		<div class="col-4"></div>
	</div>
	<div class = "row">
	<div class="col-1"></div>
		<div class="col-3">Date : <?php 
		echo $this->dtparam;		
	?> </div>
		<div class="col-3">Route : <?php 		
		echo $this->rtparam;
	?></div>
		<div class="col-3"></div>
		<div class="col-3"></div>
	</div>
    <?= $msg; ?>
	
	<br /><br />
	<div style="margin: 10px">
    <table id="example" class='table table-info table-striped table-bordered' style="width:100%; font-size : 12px; color: black; !important">
        <thead>         
			
			<tr>   
				<th>ROUTECODE</th>
				<th>SALESMAN</th>	
				<th>TYPE</th>										
				<th>INVOICE NO</th>
				<th>TRANSACTION DATE</th>
				<th>AGAINST INVOICE</th>
				<th>SALES INV DATE</th>				
				<th>CUSTOMER CODE</th>					
				<th>CUSTOMER NAME</th>
				<th>PAY TYPE</th>
				<th>CHEQ NUNBER</th>
				<th>CHEQ DATE</th>
				<th>BANK NAME</th>			
				<th>AMOUNT</th>	
				<th>CASH AMOUNT</th>
				<th>CHEQUE AMOUNT</th>	
				<th>LOCATION</th>
				<th>COMMENTS</th>
				<th>DIVISION CODE</th>						
			</tr>		
			
        </thead>
        <tbody>
	
			<?php
			foreach($this->data[0] as $key => $value) 
			{
				$amt =0;
				if($value["paytype"]== 'CASH')
					$amt = $value["cashamt"];
				if($value["paytype"]== 'CHEQUE')
					$amt = $value["checkamt"];
			?>
				<tr>					
					
					<td><?php echo $value["routecode"] ; ?> </td>
					<td><?php echo $value["salesmancode"] ; ?> - <?php echo $value["salesmanname1"] ; ?></td>					
					<td><?php echo $value["type"] ; ?></td>					
					<td><?php echo $value["invoicenumber"] ; ?></td>
					<td><?php echo $value["transactiondate"] ; ?></td>
					<td><?php echo $value["againstinv"] ; ?></td>
					<td><?php echo $value["saleinvoiceddate"] ; ?></td>
					<td><?php echo $value["customercode"] ; ?></td>
					<td><?php echo $value["customername"] ; ?></td>
					<td><?php echo $value["paytype"] ; ?></td>
					<td><?php echo $value["checknumber"] ; ?></td>
					<td><?php echo $value["checkdate"] ; ?></td>	
					<td><?php echo $value["bankname"] ; ?></td>					
					<td><?php echo $amt ; ?></td>					
					<td><?php echo $value["cashamt"] ; ?></td>
					<td><?php echo $value["checkamt"]; ?></td>
					<td><?php echo $value["arbroutename"] ; ?> </td>
					<td><?php echo $value["comments"] ; ?></td>
					<td><?php echo $value["divisioncode"] ; ?></td>
				</tr>
			<?php			
			}
			?>
        </tbody>
    </table>
	</div>
</div>
