<?php
    $this->translate = Zend_Registry::get('Zend_Translate');
?>
<table id="search" ></table>
<div id="pagersr"></div>

<script  type="text/javascript">
var decimalplaces = <?php echo $this->decimalplaces; ?>;
jQuery("#search").jqGrid({
   	url:base_url+"/reports/customervisitdet/customervisitdet/",
	datatype: "json",
   	colNames:['<?php echo $this->translate->_('Trip ID');?>','<?php echo $this->translate->_('Transaction Date');?>','<?php echo $this->translate->_('Route Code');?>','<?php echo $this->translate->_('Route Name');?>','<?php echo $this->translate->_('Salesman Code');?>','<?php echo $this->translate->_('Salesman Name');?>','<?php echo $this->translate->_('Customer Code');?>','<?php echo $this->translate->_('Customer');?>','<?php echo $this->translate->_('Channel');?>','<?php echo $this->translate->_('Visit Scheduled');?>','<?php echo $this->translate->_('Serviced');?>'],
   	colModel:[
		{name:'routekey',index:'routekey', width:50},
        {name:'transactiondate',index:'transactiondate', width:70, align:"right"},
   		{name:'alternateroutecode',index:'alternateroutecode', width:70, align:"right"},
        {name:'routename',index:'routename', width:100, align:"right"},
        {name:'alternatesalesmancode',index:'alternatesalesmancode', width:70, align:"right"},
        {name:'salesmanname1',index:'salesmanname1', width:150, align:"right"},
		{name:'customeraltcode',index:'customeraltcode', width:70, align:"right"},
        {name:'customername',index:'customername', width:170, align:"right"},
		{name:'channelname',index:'channelname', width:70, align:"right"},
		{name:'schelduledflag',index:'schelduledflag', width:70, align:"right"},
		{name:'servicedflag',index:'servicedflag', width:70, align:"right"}
		
	],
	<?php if($this->css == 'ar_') { ?>
        direction :"rtl", 
    <?php } ?>
    height: 'auto',
    width: 'auto',
   	rowNum:eval(RP_NOOFRECORDSHOW),
   	rowList:eval(RP_ROWLISTSHOW),
    pager: '#pagersr',
   	sortname: 'routecode',
	viewrecords:true,
	sortorder: "desc",
   	footerrow : true,
	userDataOnFooter : true,
	altRows : false,
	grouping:false,
	groupingView :
    {
        groupField : ['route'],
        groupColumnShow : [false],
        groupCollapse : false,
        groupOrder: ['asc'] ,
        groupSummary : [false],
        groupDataSorted : true,
    }
});

jQuery("#search").jqGrid('navGrid','#pagersr',
{
	edit:false,add:false,del:false,search:false,refresh:false
},
{}, // edit options
{}, // add options
{}, //del options
{multipleSearch:false,showQuery: false} // search options,

);


jQuery("#xlsexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
jQuery("#csvexport").click( function() {
    var sortname = $("#search").jqGrid('getGridParam',"sortname");
    var sortorder = $("#search").jqGrid('getGridParam',"sortorder");
    var exporturl = $(this).attr('href')+"?sidx="+sortname+"&sord="+sortorder;
    document.location.href = exporturl;
    return false;
});
</script>