<style>
.margin_zero {margin-top:0px !important;}
</style>
<script>
$(document).ready(function(){
	$("#selectedall").click(function(){
		var mslids = "";
		$( "input[name='chk[]']" ).prop( "checked", function( i, val ) {
			if($(this).is(':checked')) {
				var vals = this.value;
				$("#enforcemsl_"+vals+"").prop( "checked","checked");
				$("#enforcemsl_"+vals+"").val(1);
				 mslids += vals+",";
			}	
		});
	});
	$("#unselectedall").click(function(){
		var mslids = "";
		$( "input[name='chk[]']" ).prop( "checked", function( i, val ) {
			if($(this).is(':checked')) {
				var vals = this.value;
				$("#enforcemsl_"+vals+"").prop( "checked",false);
				$("#enforcemsl_"+vals+"").val(1);
				 mslids += vals+",";
			}	
		});
	});
	$("#enforceall").click(function(){
		var mslids = "";
		$( "input[name='chk[]']" ).prop( "checked", function( i, val ) {
			if($(this).is(':checked')) {
				var vals = this.value;
				$("#enforcemsl_"+vals+"").prop( "checked","checked");
				$("#enforcemsl_"+vals+"").val(1);
				 mslids += vals+",";
			}	
		});
		if(mslids != ""){
		$.ajax({
				type : "POST",
				url : base_url+"/account/customer/saveitemmustcustomer/enforce/1/mslids/"+mslids,
				success:function(returndata){
					alert(returndata); 
				}
			});
		}else{
			alert("Please Select a customer");
			return false;
		}
	});
	$("#unenforceall").click(function(){
		var mslids = "";
		$( "input[name='chk[]']" ).prop( "checked", function( i, val ) {
			if($(this).is(':checked')) {
				var vals = this.value;
				$("#enforcemsl_"+vals+"").prop( "checked",false);
				$("#enforcemsl_"+vals+"").val(1);
				 mslids += vals+",";
			}	
		});
		if(mslids != ""){
		$.ajax({
				type : "POST",
				url : base_url+"/account/customer/saveitemmustcustomer/enforce/0/mslids/"+mslids,
				success:function(returndata){
					alert(returndata); 
				}
			});
		}else{
			alert("Please Select a customer");
			return false;
		}
	});
});	
</script>
<?php if(SFA_Message::isErrorMsg()) {  ?>
    <div class="alert error">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getErrorMsg(); ?></strong>
    </div>
<?php } ?>
<?php if(SFA_Message::isSetMsg()) {  ?>
    <div class="alert success">
        <span class="icon"></span><span class="hide">x</span><strong><?php echo SFA_Message::getMsg(); ?></strong>
    </div>
<?php } ?>
<form name="frmoverview" id="frmoverview" action="" method="post">
    <input type="hidden" id="hdDelete" name="hdDelete" value="" />
<div class="grid_12" id="item-grid">
    <div class="box">
        <div class="header">
            <div class="_50_3 back_btn">
				<img src="<?php echo $this->baseUrl()?>/public/images/icon_accountreceivables.png" class="margin_top_7">
				<h3><?php echo $this->title?></h3>
	    	</div>
			<!--<div class="_50_3">
		
				<?php if($this->checkaccess("delete")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" name="btndelete" id="btndelete"></div><?php } ?>
				<?php if($this->checkaccess("update")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnedit" name="btnedit"></div><?php } ?>
				<?php if($this->checkaccess("insert")) { ?><div class="_10 save_btn"><input class="border_none" type="button" value="" id="btnadd" name="btnadd" onclick="winloc('<?php echo $this->url(array("module"=>"account","controller"=>"customer","action"=>"additemmust"), "default", true);?>')"></div><?php } ?>
			</div>-->
        </div>
		<div class="_100">
			<div class="_5_4" >
				<input type="checkbox"  name="selectedall" value ="0"  id="selectedall">
			</div>	
			<div class="_15_3">
				<input type="button"  name="enforceall" value ="      Enforceall" id="enforceall">
			</div>	
			<div class="_5_4" style="text-align:right">
				<input type="checkbox"  name="unselectedall" value ="0"  id="unselectedall">
			</div>	
			<div class="_15_3">
				<input type="button"  name="unenforceall" value ="     UnEnforceall" id="unenforceall">
			</div>	
		</div>
	<div class="clear"></div>
	<div class="clear"></div>
	<?php echo $this->partial('datagrid_ajax_msl.phtml', $this); ?>
	
    <div class="clear"></div>
    </div> <!-- End of .box -->
</div> <!-- End of .grid_12 -->
</form>