<?php
/**
* @name       routestartenddays.phtml
* @since      16 feb, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
	
<link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css">

    <!-- Custom styles for this template -->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css">


<div class="card shadow margin-info" style="margin: 20px">
	<div class = "row">
		<div class="col-4"></div>
		<div class="col-4"><p class="text-center"><b><u>Daiyly Route Track</u></b></p></div>
		<div class="col-4"></div>
	</div>
	<div class = "row">
	<div class="col-1"></div>
		<div class="col-3">Year-Month : <?php 
		echo $this->dtparam;		
	?> </div>
		<div class="col-3">Route : <?php 		
		echo $this->rtparam;
	?></div>
		<div class="col-3"></div>
		<div class="col-3"></div>
	</div>
    <?= $msg; ?>
	
	<br /><br />
	<div style="margin: 10px">
    <table id="example" class='table table-striped table-bordered' style="width:100%; font-size : 12px; color: black; !important">
        <thead>
            <tr>                
				<th>SALESMAN CODE</th>		
				<th>SALESMAN NUMBER</th>
				<th>SALESMAN NAME</th>
				<th>DAY</th>
				<th>ROUTE START DATE</th>								
				<th>ROUTE START TIME</th>								
				<th>ROUTE END DATE</th>
				<th>ROUTE END TIME</th>								
				<th>ROUTE DURATION</th>						
				<th>FIRST CUST GEO</th>
				<th>FIRST CUST START TIME</th>
				<th>LAST CUST GEO</th>
				<th>LAST CUST CHECK OUT TIME</th>
				<th>TOTAL HOURS</th>
				<th>START KM</th>
				<th>END KM</th>
				<th>TOTAL KM</th>
			</tr>
        </thead>
        <tbody>
	
			<?php
			foreach($this->data[0] as $key => $value) 
			{
			?>
				<tr>					
					<td><?php echo $value["salesmancode"] ; ?></td>
					<td><?php echo $value["ansalesmancode"] ; ?></td>
					<td><?php echo $value["salesmanname1"] ; ?></td>					
					<td><?php echo $value["dayname"] ; ?></td>
					<td><?php echo $value["routestartdate"] ; ?></td>			
					<td><?php echo $value["routestarttime"] ; ?></td>								
					<td><?php echo $value["ROUTEENDDATE"] ; ?></td>
					<td><?php echo $value["routeendtime"] ; ?></td>			
					<td><?php echo $value["rdur"] ; ?></td>
					<td><?php echo $value["FIRSTGEO"] ; ?></td>
					<td><?php echo $value["FIRSTTIME"] ; ?></td>
					<td><?php echo $value["LASTGEO"] ; ?></td>
					<td><?php echo $value["LASTTIME"] ; ?></td>
					<td><?php echo $value["totime"] ; ?></td>
					<td><?php echo $value["routestartodometer"] ; ?></td>
					<td><?php echo $value["routeendodometer"] ; ?></td>
					<td><?php echo $value["totkm"] ; ?></td>					
				</tr>
			<?php			
			}
			?>
        </tbody>
    </table>
	</div>
</div>
<script type="text/javascript" src= "https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script>
<script type="text/javascript" src= "https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').dataTable({
				scrollX: true,
				paging: false,
				scrollCollapse: true,
				scrollY: '400px',
                dom: 'Bfrtip',
				"columnDefs": [
    { "width": "10%", "targets": 1 }
  ],
                buttons: [
                    {
                    extend: 'excelHtml5',
                    title: 'routedailytrack'
                },
                {
                    extend: 'pdfHtml5',
                    title: 'routedailytrack'
                }
                ]
            });

        });
    </script>