<!--Source code -->
<!-- Style to put some height on the map -->
<style type="text/css"><style>
#content{background-image:none!important;}
#main_content{width: 100% !important;}
#header,#colors-switcher{display:none;}
aside{display:none;}
footer{display:none;}
#content{background:none!important;}

.nodata_message {
    color: #ff0000;
    font-size: 14px;
    padding: 10px;
    text-align: center;
}
.content {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background: #fff none repeat scroll 0 0;
    border-color: #2b5177 #c8c8c8 #c8c8c8;
    border-image: none;
    border-radius: 0 0 3px 3px;
    border-style: solid;
    border-width: 1px;
    padding: 0;
}


</style>
</style>
<?php
$mapdata = $this->mapdata;
$startmapdata = $this->startmapdata;
$showcustomer = $this->showcustomer;
$routepath = $this->routepath;
?>
<!-- Load the Google Maps aPI -->
<script src="http://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyA1tLicnmjy5h3qD2IDGOPOocTbVOXIYRo"></script>
<!-- All of the script for multiple requests -->
<script type="text/javascript">

    // Initialise some variables
    var directionsService = new google.maps.DirectionsService();
    var num, map, data;
    var requestArray = [], renderArray = [];
	
    // A JSON Array containing some people/routes and the destinations/stops
	//var startArray = ["<?php echo $startmapdata[0]['latitude'];?>, <?php echo $startmapdata[0]['longitude'];?>"];
	//var finishArray = ["<?php echo $startmapdata[1]['latitude'];?>, <?php echo $startmapdata[1]['longitude'];?>"];
    var jsonArray = {
			<?php
	if(count($mapdata) > 0)
	{
	
		for($i=0;$i<=count($mapdata);$i++)
		{
			$comma =",";
			if($i == count($mapdata) )
			{
				$comma="";
			}
			if($showcustomer ==  '1'){
			?>
			"<?php echo $mapdata[$i]['routecode'];?>":[<?php echo $routepath;?>] 
		//"<?php echo $mapdata[$i]['customercode'];?>": ["<?php echo $mapdata[$i]['latitude'];?>,<?php echo $mapdata[$i]['longitude'];?>"]<?php echo $comma;?>
		<?php
			}else {
			?>
        "<?php echo $mapdata[$i]['routecode'];?>": ["<?php echo $mapdata[$i]['startlatitude'];?>,<?php echo $mapdata[$i]['startlongitude'];?>","<?php echo $mapdata[$i]['midlatitude'];?>,<?php echo $mapdata[$i]['midlongitude'];?>","<?php echo $mapdata[$i]['endlatitude'];?>,<?php echo $mapdata[$i]['endlongitude'];?>"]<?php echo $comma;?>
		<?php
			
			}  
		}?>
		<?php 
	}
	?>	
    }
    
    // 16 Standard Colours for navigation polylines
    var colourArray = ['navy', 'grey', 'fuchsia', 'black', 'white', 'lime', 'maroon', 'purple', 'aqua', 'red', 'green', 'silver', 'olive', 'blue', 'yellow', 'teal'];
	var reasonarray ={"ZERO_RESULTS":["Route Couldn`t be Found Between the Origin and Destination"], "MAX_WAYPOINTS_EXCEEDED":["Too Many DirectionsWaypoint Fields were provided in the DirectionsRequest"], "NOT_FOUND":["One of the locations specified in the request's origin, destination, or waypoints could not be geocoded"],"INVALID_REQUEST":["DirectionsRequest was invalid"], "OVER_QUERY_LIMIT":["Too many requests within the allowed time period"], "REQUEST_DENIED":["Webpage is not allowed to use the directions service"],"UNKNOWN_ERROR":["Directions request could not be processed due to a server error"]};
	// for more det: https://developers.google.com/maps/documentation/javascript/directions#TravelModes  in Status of Directions Query
    // Let's make an array of requests which will become individual polylines on the map.
    function generateRequests(){
        requestArray = [];
		
		
        for (var route in jsonArray){
            var waypts = [];
            var start, finish;
            var lastpoint;

            data = jsonArray[route]
            limit = data.length
            for (var waypoint = 0; waypoint < limit; waypoint++) {
                if (data[waypoint] === lastpoint){
                    continue;
                }
                
                lastpoint = data[waypoint]
                waypts.push({
                    location: data[waypoint],
                    stopover: false
                });

            }

            start = (waypts.shift()).location;//startArray;
            finish =waypts.pop();//finishArray; 
            if(finish === undefined){
                finish = start;
            } else {
                finish = finish.location;
            }
            var request = {
                origin: start,
                destination: finish,
                waypoints: waypts,
				optimizeWaypoints: true,
                travelMode: google.maps.TravelMode.DRIVING
            };
			
            requestArray.push({"route": route, "request": request});
        }

        processRequests();
    }
	var arrayName = <?php echo json_encode($mapdata); ?>;
    function processRequests(){

        var i = 0;

        function submitRequest(){
			if(requestArray[i]!== undefined){
            	directionsService.route(requestArray[i].request, directionResults);
			}
        }
        function directionResults(result, status) {
            if (status == google.maps.DirectionsStatus.OK) {

				var myHtml = "<table style='width:100%;'><tr><td><b>" + "Route:"+arrayName[i]['routecode'] + "</b></td></tr><tr><td><b>" + "Salesman:"+arrayName[i]['salesmancode'] + "</b><b>" + "Customer:"+arrayName[i]['customercode'] + "</b></td></tr></table>";
				var infowindow_forRoutedMarker = new google.maps.InfoWindow({				
                content: myHtml				
				});	

                renderArray[i] = new google.maps.DirectionsRenderer();
                renderArray[i].setMap(map);				

               renderArray[i].setOptions({
                    preserveViewport: true,
                    suppressInfoWindows: true,					
					infoWindow: infowindow_forRoutedMarker,					
                    suppressMarkers: true,											
					markerOptions: ({ clickable: true,							
					title:"Route:"+arrayName[i]['routecode'] + " " + "Customer:"+arrayName[i]['customercode'] + " " + "Salesman:"+arrayName[i]['salesmancode']+ " " + "Start Time:"+arrayName[i]['starttime']+ " " + "End Time:"+arrayName[i]['endtime'],zIndex: 3 }),						
					polylineOptions: {
                        strokeWeight: 4,
                        strokeOpacity: 0.8,
                        strokeColor: colourArray[i]
                    }		
                });	
				 
                // Use this new renderer with the result
                renderArray[i].setDirections(result);
                // and start the next request
                nextRequest();

            }else {
				alert(reasonarray[status]);
			}

        }
		
        function nextRequest(){
            // Increase the counter
            i++;
            // Make sure we are still waiting for a request
            if(i >= arrayName.length){
                // No more to do
                return;
            }
            // Submit another request
            submitRequest();
			
        }
		

        // This request is just to kick start the whole process
        submitRequest();
    }
    // Called Onload
	var directionsDisplay;
	var directionsService = new google.maps.DirectionsService();

    function init() {
		directionsDisplay = new google.maps.DirectionsRenderer();
        var mapOptions = {
         	center: new google.maps.LatLng(<?php echo $mapdata[0]['latitude'];?>, <?php echo $mapdata[0]['longitude'];?>),
            zoom: 12,
            mapTypeControl: false,
            streetViewControl: false,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
		
            
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
	
        // Start the request making	
        generateRequests();
		showMarker(map);

    }
	function showMarker(map){
		var arrayName = <?php echo json_encode($mapdata); ?>;
		 var contentString =[];
		  var iconstr = '';//'http://maps.google.com/mapfiles/ms/icons/green-dot.png';
		 for (var k = 0; k <= Object.keys(arrayName).length; k++) {
		   contentString[k] = '<div id="content">'+"Route:" +arrayName[k].routename + "  " + "salesman:" +arrayName[k].salesmanname1 + "  " +  "Customer:" +arrayName[k].customername +'</div>';
			   if(arrayName[k].schelduledflag == 0 && arrayName[k].servicedflag == 1){
					iconstr = 'http://maps.google.com/mapfiles/ms/icons/green-dot.png';
			   }else {
					iconstr = 'http://maps.google.com/mapfiles/ms/icons/red-dot.png';
			   }
			  var marker = new google.maps.Marker({
				position: new google.maps.LatLng(arrayName[k].latitude,arrayName[k].longitude),
				map: map,
				title:"Customer:"+arrayName[k]['customername']+"\n"+"Lat:"+arrayName[k]['latitude']+ ", " + "Long:"+arrayName[k]['longitude'],
				icon:iconstr
			  });
			  var infowindow = new google.maps.InfoWindow({
			  content: contentString[k]
			});
			google.maps.event.addListener(marker, 'click', (function(marker, k) {
				return function() {
					infowindow.setContent(contentString[k]);
					infowindow.open(map, marker);
				}
			})(marker, k));

		  }
	}
        
    // Get the ball rolling and trigger our init() on 'load'
    google.maps.event.addDomListener(window, 'load', init);
</script>

<!-- Somewhere in the DOM for the map to be rendered -->
<?php
if($mapdata!= NULL)
{	
?>
<div id="map-canvas" style="width:100%;height:670px;" ></div>
<?php
}
else{
?>
<div class="content  min_height_10"><div class="clear_only nodata_message margin_top_50 margin_bottom_10"><b>No Record(s) Found.</b></div>					</div>
<?php
}
?>