<?php
/**
* @name       routestartenddays.phtml
* @since      16 feb, 2012
* @version    Release: 1.0
* @author     HD <hiren.d@elantechnologies.com>
* @copyright  2011 Elan Technologies
*
*
*/
$this->translate = Zend_Registry::get('Zend_Translate');
?>
<style>
.margin_zero {margin-top:0px !important;}
.actions {width:100%;}
.box .content {border:none !important;} td{padding:5px;}
</style>
	
<link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css">

    <!-- Custom styles for this template -->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css">


<?php
	$strdate="";
	$enddate ="";
	foreach($this->data[0] as $key => $value) 
			{
				if($value["DATEOFRUN"] != "0")
				{
					$enddate = $value["DATEOFRUN"];
					$strdate = $value["startdate"];
					break;
				}
			}
?>

<div class="card shadow margin-info" style="margin: 20px">
	<div class = "row">
		<div class="col-4"></div>
		<div class="col-4"><p class="text-center"><b><u>Route Analysis Report</u></b></p></div>
		<div class="col-4"></div>
	</div>
	<div class = "row">
	<div class="col-1"></div>
		<div class="col-3">Start Date : <?php 
		echo $strdate;		
	?> </div>
		<div class="col-3">End Date : <?php 		
		echo $enddate;
	?></div>
		<div class="col-3"></div>
		<div class="col-3"></div>
	</div>
    <?= $msg; ?>
	
	<br /><br />
	<div style="margin: 10px">
    <table id="example" class='table table-info table-striped table-bordered' style="width:100%; font-size : 12px; color: black; !important">
        <thead>
            <tr>                
				<th>DIVISION</th>
				<th>ROUTECODE</th>
				<th>ROUTE TYPE</th>
				<th>REGION</th>
				<th>OPEN CUST COUNT</th>
				<th>CURRENT CUST COUNT</th>	
				<th>ADDED CUST COUNT</th>					
				<th>ACTUAL VISIT</th>
				<th>STRIKE RATE</th>						
				<th>MTD SALE</th>
				<th>INV COUNT</th>
				<th>AVG NPS</th>
				<th>INV COUNT < 30 OMR</th>
				<th>CUST COUNT < 12 LINES</th>
				<th>AVG CALLS</th>
				<th>AVG LINES</th>
				<th>MUST HAVE SKU SAL</th>
				<th>AVG SKU</th>
			</tr>
        </thead>
        <tbody>
	
			<?php
			foreach($this->data[0] as $key => $value) 
			{
			?>
				<tr>					
<td><?php echo $value["divisioncode"] ; ?></td>
<td><?php echo $value["routecode"] ; ?></td>
<td><?php echo $value["routetype"] ; ?></td>
<td><?php echo $value["region"] ; ?></td>
<td><?php echo $value["cust_count_beg"] ; ?></td>
<td><?php echo $value["tot_cust"] ; ?></td>
<td><?php echo $value["added_cust"] ; ?></td>
<td><?php echo $value["actual_visit"] ; ?></td>
<td><?php echo $value["strke_rate"] ; ?></td>
<td><?php echo $value["mtd_sale"] ; ?></td>
<td><?php echo $value["INVCOUNT"] ; ?></td>
<td><?php echo $value["avg_nps"] ; ?></td>
<td><?php echo $value["inv_lt_30"] ; ?></td>
<td><?php echo $value["cust_lt_12_lines"] ; ?></td>
<td><?php echo $value["avg_calls"] ; ?></td>
<td><?php echo $value["avg_lines"] ; ?></td>
<td><?php echo $value["must_have_sku_sale"] ; ?></td>
<td><?php echo $value["AVGSKU"] ; ?></td>

				</tr>
			<?php			
			}
			?>
        </tbody>
    </table>
	</div>
	
	Open Cust Count : Number of actve customers as on the beginning of the Month</br>
	Current Cust Count : Number of actve customers as on the Running Date</br>
	Added Cust Count : Newly added customers during the period</br>
	Actual Visit : No of distinct customers visited during the priod</br>
	Strike Rate : Percentage of succesfull vists(atleast one txn done) against Actual Visit </br>
	Avg NPS : Average Invoice amount against Total Custoemrs</br>
	Inv Count < 30 OMR : Number of Invoices with amount lesss than 30 OMR</br>
	Cust Count < 12 Lines : Number of Distinct Customers with lesss than 12 items in invoice</br>
	Avg Calls : Average Success visits agaist No of Working days(Route Started) </br>
	Avg lines : Average number of lines agaist Total Invoices </br>
	Avg SKU : Route-wise average of Customer-wise Distinct items in invoices </br>
	
</div>
<script type="text/javascript" src= "https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script>
<script type="text/javascript" src= "https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').dataTable({
				scrollX: true,
				paging: false,
				scrollCollapse: true,
				scrollY: '400px',
                dom: 'Bfrtip',
				"columnDefs": [
    { "width": "10%", "targets": 2 }
  ],
                buttons: [
            {
                extend: 'excelHtml5',
                title: 'Route-Customer-Analysis'
            },
            {
                extend: 'pdfHtml5',
                title: 'Route-Customer-Analysis'
            }
        ]
            });

        });
    </script>